[package]
name = "pilspector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = "1.3.0"
serde = { version = "1.0.148", features = ["serde_derive"] }
serde_json = "1.0.89"
